//! R2004 container (ODA spec chapter 4), also used unchanged by R2010, R2013 and
//! R2018 (chapters 6–8).
//!
//! Layout: a 0x80-byte plain header, then 0x6C bytes XOR-masked with a fixed LCG
//! sequence (the "2004 file header data"), a page map and a section map stored in
//! compressed *system pages*, and data sections split into 32-byte-masked,
//! LZ77-compressed *data pages*.

use std::collections::{BTreeMap, HashSet};

use cadkit_core::bytes::ByteReader;
use cadkit_core::{Error, Limits, Result};

use super::{Budget, Container, MAX_SYSTEM_PAGE, Section, SectionBuffer, context, lz77_r2004};
use crate::crc::{crc32, page_checksum};
use crate::version::DwgVersion;

/// Largest accepted page size; the sections this reader uses have 0x7400.
const MAX_PAGE_SIZE: usize = 0x10_0000;
/// Section page type of the page map system page.
const PAGE_MAP_TYPE: u32 = 0x4163_0E3B;
/// Section page type of the section map system page.
const SECTION_MAP_TYPE: u32 = 0x4163_003B;
/// Section page type of every data page.
const DATA_PAGE_TYPE: u32 = 0x4163_043B;
/// "AcFssFcAJMB\0".
const FILE_ID: &[u8; 12] = b"AcFssFcAJMB\0";

/// The 0x6C-byte XOR mask of §4.1, generated by the LCG the spec prints.
pub fn header_mask() -> [u8; 0x6C] {
    let mut out = [0u8; 0x6C];
    let mut seed: u32 = 1;
    for byte in &mut out {
        seed = seed.wrapping_mul(0x343FD).wrapping_add(0x269EC3);
        *byte = (seed >> 16) as u8;
    }
    out
}

/// Decrypted 2004 file header data (§4.1), only the fields the reader uses.
#[derive(Debug, Clone, Copy)]
pub struct FileHeaderData {
    /// Section page map id.
    pub page_map_id: u32,
    /// File address of the page map (already + 0x100).
    pub page_map_address: u64,
    /// Page id of the section map.
    pub section_map_id: u32,
}

/// One entry of a section's local page list (§4.5).
#[derive(Debug, Clone, Copy)]
struct PageRef {
    page_number: i32,
    data_size: u32,
    start_offset: u64,
}

/// A data section description (§4.5).
#[derive(Debug, Clone)]
struct SectionInfo {
    size: u64,
    max_page_size: u32,
    compressed: u32,
    encrypted: u32,
    pages: Vec<PageRef>,
}

fn read_file_header(bytes: &[u8], c: &mut Container<'_>) -> Result<FileHeaderData> {
    let mut r = ByteReader::new(bytes);
    r.skip(0x0B)?;
    c.maintenance = r.u8()?;
    r.skip(7)?;
    c.codepage = r.u16()?;
    r.skip(3)?;
    let security = r.u32()?;
    if security & 0x0001 != 0 {
        return Err(Error::Unsupported(
            "password-encrypted DWG data sections".into(),
        ));
    }
    r.seek(0x80)?;
    let masked = r.array::<0x6C>()?;
    let mask = header_mask();
    let mut data = [0u8; 0x6C];
    for ((d, m), k) in data.iter_mut().zip(masked.iter()).zip(mask.iter()) {
        *d = m ^ k;
    }
    if data.get(..12) != Some(&FILE_ID[..]) {
        return Err(Error::invalid(
            0x80,
            "R2004 file header id is not AcFssFcAJMB",
        ));
    }
    let mut h = ByteReader::with_base(&data, 0x80);
    h.seek(0x50)?;
    let page_map_id = h.u32()?;
    let page_map_address = h
        .u64()?
        .checked_add(0x100)
        .ok_or_else(|| h.invalid("page map address"))?;
    let section_map_id = h.u32()?;
    h.seek(0x68)?;
    let stored_crc = h.u32()?;
    let mut zeroed = data;
    if let Some(field) = zeroed.get_mut(0x68..0x6C) {
        field.fill(0);
    }
    let computed = crc32(0, &zeroed);
    if computed != stored_crc {
        c.warn(
            "dwg.crc_mismatch",
            format!("R2004 file header CRC {stored_crc:#010x}, computed {computed:#010x}"),
            Some(0xE8),
        );
    }
    Ok(FileHeaderData {
        page_map_id,
        page_map_address,
        section_map_id,
    })
}

/// Reads and decompresses a system page (§4.3) at `address`.
fn read_system_page(
    bytes: &[u8],
    address: u64,
    expected_type: u32,
    budget: &mut Budget,
    c: &mut Container<'_>,
) -> Result<Vec<u8>> {
    let start =
        usize::try_from(address).map_err(|_| Error::invalid(address, "system page address"))?;
    let mut r = ByteReader::with_base(
        bytes.get(start..).ok_or(Error::Truncated {
            offset: address,
            needed: 0x14,
        })?,
        address,
    );
    let header = r.peek(0x14)?;
    let page_type = r.u32()?;
    if page_type != expected_type {
        return Err(Error::invalid(
            address,
            format!("system page type {page_type:#010x}, expected {expected_type:#010x}"),
        ));
    }
    let decompressed = r.u32()?;
    let compressed = r.u32()?;
    let compression = r.u32()?;
    let checksum = r.u32()?;
    if u64::from(decompressed) > MAX_SYSTEM_PAGE {
        return Err(Error::invalid(
            address,
            format!("system page of {decompressed} bytes"),
        ));
    }
    let data = r.bytes(compressed as usize)?;

    let mut hdr = [0u8; 0x14];
    hdr.copy_from_slice(header);
    if let Some(field) = hdr.get_mut(0x10..0x14) {
        field.fill(0);
    }
    let computed = page_checksum(page_checksum(0, &hdr), data);
    if computed != checksum {
        c.warn(
            "dwg.checksum_mismatch",
            format!("system page checksum {checksum:#010x}, computed {computed:#010x}"),
            Some(address),
        );
    }
    // Reserve the declared size, then charge only what was produced (the output grows
    // with the decompressed data, never to the declared size up front).
    let size = budget.take(u64::from(decompressed))?;
    let out = if compression == 2 {
        lz77_r2004::decompress(data, size, address + 0x14)
    } else {
        Ok(data.get(..size.min(data.len())).unwrap_or(&[]).to_vec())
    };
    budget.refund(size - out.as_ref().map_or(0, |o| o.len().min(size)));
    let out = out?;
    if compression == 2 && out.len() != size {
        c.warn(
            "dwg.size_mismatch",
            format!(
                "system page decompressed to {} bytes, header says {size}",
                out.len()
            ),
            Some(address),
        );
    }
    Ok(out)
}

/// Parses the page map (§4.4): page number → (file address, size).
fn parse_page_map(data: &[u8]) -> Result<BTreeMap<i32, (u64, u64)>> {
    let mut map = BTreeMap::new();
    let mut r = ByteReader::new(data);
    let mut address: u64 = 0x100;
    while r.remaining() >= 8 {
        let number = r.i32()?;
        let size = u64::from(r.u32()?);
        if number >= 0 {
            map.insert(number, (address, size));
        } else {
            // Gap record: parent, left, right, 0.
            r.skip(16)?;
        }
        address = address
            .checked_add(size)
            .ok_or_else(|| r.invalid("page map address overflow"))?;
    }
    Ok(map)
}

/// Parses the section map (§4.5): section name → description.
fn parse_section_map(data: &[u8], max_pages: usize) -> Result<BTreeMap<String, SectionInfo>> {
    let mut r = ByteReader::new(data);
    let count = r.u32()?;
    r.skip(16)?;
    let mut sections = BTreeMap::new();
    for _ in 0..count {
        if r.at_end() {
            break;
        }
        let size = r.u64()?;
        let page_count = r.u32()?;
        let max_page_size = r.u32()?;
        let _unknown = r.u32()?;
        let compressed = r.u32()?;
        let _section_id = r.u32()?;
        let encrypted = r.u32()?;
        let name_bytes = r.bytes(64)?;
        let name_len = name_bytes.iter().position(|&b| b == 0).unwrap_or(64);
        let name = String::from_utf8_lossy(name_bytes.get(..name_len).unwrap_or(&[])).into_owned();
        if page_count as usize > max_pages
            || (page_count as usize).saturating_mul(16) > r.remaining()
        {
            return Err(r.invalid(format!("section {name:?} claims {page_count} pages")));
        }
        let mut pages = Vec::with_capacity(page_count as usize);
        for _ in 0..page_count {
            let page_number = r.i32()?;
            let data_size = r.u32()?;
            let start_offset = r.u64()?;
            pages.push(PageRef {
                page_number,
                data_size,
                start_offset,
            });
        }
        sections.insert(
            name,
            SectionInfo {
                size,
                max_page_size,
                compressed,
                encrypted,
                pages,
            },
        );
    }
    Ok(sections)
}

/// The pages of a section that are read: each page number, file page and start
/// offset once (repeats in a corrupt map would otherwise be decompressed again for
/// free), in start-offset order, with their file addresses.
fn unique_pages(
    name: &str,
    info: &SectionInfo,
    page_map: &BTreeMap<i32, (u64, u64)>,
    c: &mut Container<'_>,
) -> Vec<(PageRef, u64)> {
    let (mut numbers, mut addresses, mut starts) = (HashSet::new(), HashSet::new(), HashSet::new());
    let mut pages = Vec::new();
    let mut repeated = 0usize;
    for page in &info.pages {
        let Some(&(address, _)) = page_map.get(&page.page_number) else {
            c.warn(
                "dwg.missing_page",
                format!("section {name}: page {} not in page map", page.page_number),
                None,
            );
            continue;
        };
        if !numbers.insert(page.page_number)
            || !addresses.insert(address)
            || !starts.insert(page.start_offset)
        {
            repeated += 1;
            continue;
        }
        pages.push((*page, address));
    }
    if repeated > 0 {
        c.warn(
            "dwg.duplicate_page",
            format!("section {name}: {repeated} repeated page references ignored"),
            None,
        );
    }
    pages.sort_by_key(|(page, _)| page.start_offset);
    pages
}

/// Assembles one data section from its pages (§4.5, §4.6).
fn read_section(
    bytes: &[u8],
    name: &str,
    info: &SectionInfo,
    page_map: &BTreeMap<i32, (u64, u64)>,
    budget: &mut Budget,
    c: &mut Container<'_>,
) -> Result<Vec<u8>> {
    if info.encrypted == 1 {
        return Err(Error::Unsupported(format!("encrypted section {name}")));
    }
    let page_size = info.max_page_size as usize;
    if page_size == 0 || page_size > MAX_PAGE_SIZE {
        return Err(Error::invalid(
            0,
            format!("section {name} has page size {page_size:#x}"),
        ));
    }
    let pages = unique_pages(name, info, page_map, c);
    // Plausibility bound on the declared size: the listed pages (each at most one page
    // and at most ~255x its compressed size with this LZ77 variant) plus a few omitted
    // zero pages.
    let stored: u64 = pages
        .iter()
        .map(|(p, _)| {
            let ratio_bound = if info.compressed == 2 {
                u64::from(p.data_size) * 256 + 0x400
            } else {
                u64::from(p.data_size)
            };
            ratio_bound.min(page_size as u64)
        })
        .sum();
    let plausible = stored.saturating_add(64 * page_size as u64);
    let mut size = info.size;
    if size > plausible {
        c.warn(
            "dwg.section_size",
            format!("section {name} claims {size} bytes; using {plausible}"),
            None,
        );
        size = plausible;
    }
    let total = usize::try_from(size)
        .map_err(|_| Error::LimitExceeded(format!("section {name} of {size} bytes")))?;
    let mut out = SectionBuffer::new(total, page_size as u64);
    for (page, address) in pages {
        let Ok(start) = usize::try_from(page.start_offset) else {
            continue;
        };
        if start >= total {
            continue;
        }
        // Each decompression is charged: at most one page, refunded down to its output.
        let reserved = budget.take(page_size as u64)?;
        let data = read_data_page(bytes, address, info, page.data_size, page_size, c);
        budget.refund(reserved - data.as_ref().map_or(0, |d| d.len().min(reserved)));
        match data {
            Ok(data) => {
                if !out.place(start, &data, budget)? {
                    c.warn(
                        "dwg.section_gap",
                        format!(
                            "section {name}: page at {start:#x} leaves too large a gap; skipped"
                        ),
                        Some(address),
                    );
                }
            }
            Err(e) => c.warn(
                "dwg.page_error",
                format!("section {name}: page at {address:#x}: {e}"),
                Some(address),
            ),
        }
    }
    let (data, missing) = out.finish(budget)?;
    if missing > 0 {
        c.warn(
            "dwg.section_size",
            format!("section {name}: last {missing} declared bytes are not covered by pages"),
            None,
        );
    }
    Ok(data)
}

/// Reads one masked data page header and its payload (§4.6).
fn read_data_page(
    bytes: &[u8],
    address: u64,
    info: &SectionInfo,
    data_size: u32,
    page_size: usize,
    c: &mut Container<'_>,
) -> Result<Vec<u8>> {
    let start = usize::try_from(address).map_err(|_| Error::invalid(address, "page address"))?;
    let tail = bytes.get(start..).ok_or(Error::Truncated {
        offset: address,
        needed: 32,
    })?;
    let mut r = ByteReader::with_base(tail, address);
    let raw = r.array::<32>()?;
    let mask = 0x4164_536B_u32 ^ (address as u32);
    let mut header = [0u8; 32];
    for (dst, chunk) in header.chunks_exact_mut(4).zip(raw.chunks_exact(4)) {
        let mut word = [0u8; 4];
        word.copy_from_slice(chunk);
        dst.copy_from_slice(&(u32::from_le_bytes(word) ^ mask).to_le_bytes());
    }
    let mut h = ByteReader::with_base(&header, address);
    let page_type = h.u32()?;
    if page_type != DATA_PAGE_TYPE {
        return Err(Error::invalid(
            address,
            format!("data page type {page_type:#010x}"),
        ));
    }
    let _section_number = h.u32()?;
    let stored_size = h.u32()?;
    if stored_size != data_size {
        c.warn(
            "dwg.size_mismatch",
            format!("data page size {stored_size} differs from section map {data_size}"),
            Some(address),
        );
    }
    let payload = r.bytes(stored_size as usize)?;
    // §4.6: data checksum over the payload (seed 0); header checksum over the decoded
    // header with its own field zeroed, seeded with the data checksum.
    h.seek(0x18)?;
    let header_checksum = h.u32()?;
    let data_checksum = h.u32()?;
    let computed_data = page_checksum(0, payload);
    let mut zeroed = header;
    if let Some(field) = zeroed.get_mut(0x18..0x1C) {
        field.fill(0);
    }
    let computed_header = page_checksum(computed_data, &zeroed);
    if computed_data != data_checksum || computed_header != header_checksum {
        c.warn(
            "dwg.checksum_mismatch",
            format!("data page checksums {data_checksum:#010x}/{header_checksum:#010x}, computed {computed_data:#010x}/{computed_header:#010x}"),
            Some(address),
        );
    }
    if info.compressed == 2 {
        lz77_r2004::decompress(payload, page_size, address + 32)
    } else {
        Ok(payload
            .get(..page_size.min(payload.len()))
            .unwrap_or(&[])
            .to_vec())
    }
}

/// Reads an R2004/R2010/R2013/R2018 file.
pub fn read<'a>(bytes: &'a [u8], version: DwgVersion, limits: &Limits) -> Result<Container<'a>> {
    let mut c = Container::new(version);
    let fh = read_file_header(bytes, &mut c).map_err(context("R2004 file header"))?;
    let mut budget = Budget::new(limits);
    // A page needs at least its 32-byte header in the file.
    let max_pages = bytes.len() / 32 + 1;

    let page_map_data = read_system_page(
        bytes,
        fh.page_map_address,
        PAGE_MAP_TYPE,
        &mut budget,
        &mut c,
    )
    .map_err(context("page map"))?;
    let page_map = parse_page_map(&page_map_data).map_err(context("page map"))?;
    if !page_map.contains_key(&(fh.page_map_id as i32)) {
        c.warn(
            "dwg.page_map",
            format!("page map id {} not listed in the page map", fh.page_map_id),
            None,
        );
    }
    let section_map_address = page_map
        .get(&(fh.section_map_id as i32))
        .map(|&(a, _)| a)
        .ok_or_else(|| {
            Error::invalid(
                0x80,
                format!("section map page {} not in page map", fh.section_map_id),
            )
        })?;
    let section_map_data = read_system_page(
        bytes,
        section_map_address,
        SECTION_MAP_TYPE,
        &mut budget,
        &mut c,
    )
    .map_err(context("section map"))?;
    let sections =
        parse_section_map(&section_map_data, max_pages).map_err(context("section map"))?;
    c.section_names = sections.keys().cloned().collect();

    for (name, slot) in [
        ("AcDb:Header", 0),
        ("AcDb:Classes", 1),
        ("AcDb:Handles", 2),
        ("AcDb:AcDbObjects", 3),
        ("AcDb:Template", 4),
    ] {
        let Some(info) = sections.get(name) else {
            if slot != 4 {
                c.warn(
                    "dwg.missing_section",
                    format!("section {name} not present"),
                    None,
                );
            }
            continue;
        };
        match read_section(bytes, name, info, &page_map, &mut budget, &mut c) {
            Ok(data) => {
                let section = Some(Section::owned(data, name));
                match slot {
                    0 => c.header = section,
                    1 => c.classes = section,
                    2 => c.handles = section,
                    3 => c.objects = section,
                    _ => c.template = section,
                }
            }
            Err(e @ Error::LimitExceeded(_)) => return Err(e),
            Err(e) => c.warn("dwg.section_error", format!("section {name}: {e}"), None),
        }
    }
    Ok(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_mask_matches_spec_table() {
        let m = header_mask();
        assert_eq!(
            &m[..16],
            &[
                0x29, 0x23, 0xBE, 0x84, 0xE1, 0x6C, 0xD6, 0xAE, 0x52, 0x90, 0x49, 0xF1, 0xF1, 0xBB,
                0xE9, 0xEB
            ]
        );
        // The spec prints only 0x5C of the 0x6C bytes; its last row is at 0x50.
        assert_eq!(
            &m[0x50..0x5C],
            &[
                0xAD, 0x4F, 0x14, 0xF2, 0x44, 0x40, 0x66, 0xD0, 0x6B, 0xC4, 0x30, 0xB7
            ]
        );
    }

    #[test]
    fn page_map_addresses_accumulate_and_skip_gaps() {
        let mut data = Vec::new();
        for (n, s) in [(1i32, 0x100u32), (2, 0x40)] {
            data.extend(n.to_le_bytes());
            data.extend(s.to_le_bytes());
        }
        data.extend((-3i32).to_le_bytes());
        data.extend(0x20u32.to_le_bytes());
        data.extend([0u8; 16]);
        data.extend(4i32.to_le_bytes());
        data.extend(0x80u32.to_le_bytes());
        let map = parse_page_map(&data).unwrap();
        assert_eq!(map.get(&1), Some(&(0x100, 0x100)));
        assert_eq!(map.get(&2), Some(&(0x200, 0x40)));
        assert_eq!(map.get(&4), Some(&(0x260, 0x80)));
        assert!(!map.contains_key(&-3));
    }

    #[test]
    fn section_map_rejects_absurd_page_counts() {
        let mut data = Vec::new();
        data.extend(1u32.to_le_bytes());
        data.extend([0u8; 16]);
        data.extend(10u64.to_le_bytes());
        data.extend(u32::MAX.to_le_bytes()); // page count
        data.extend([0u8; 20]);
        data.extend([0u8; 64]);
        assert!(parse_section_map(&data, 1000).is_err());
    }
}

#[cfg(test)]
mod budget_tests {
    use super::*;

    /// A data page at `address` (header masked as in §4.6) holding `payload` stored.
    fn data_page(address: u64, payload: &[u8]) -> Vec<u8> {
        let words = [
            DATA_PAGE_TYPE,
            1,
            payload.len() as u32,
            payload.len() as u32,
            0,
            0,
            0,
            0,
        ];
        let mask = 0x4164_536B_u32 ^ (address as u32);
        let mut out: Vec<u8> = words
            .iter()
            .flat_map(|w| (w ^ mask).to_le_bytes())
            .collect();
        out.extend(payload);
        out
    }

    #[test]
    fn system_page_is_charged_by_its_output() {
        // Declared 8 MiB, LZ77 data producing "abcd".
        let mut bytes = Vec::new();
        for w in [PAGE_MAP_TYPE, MAX_SYSTEM_PAGE as u32, 6, 2, 0] {
            bytes.extend(w.to_le_bytes());
        }
        bytes.extend([0x01, b'a', b'b', b'c', b'd', 0x11]);
        let limits = Limits::default();
        let mut budget = Budget::new(&limits);
        let mut c = Container::new(DwgVersion::R2004);
        let out = read_system_page(&bytes, 0, PAGE_MAP_TYPE, &mut budget, &mut c).unwrap();
        assert_eq!(out, b"abcd");
        assert_eq!(budget.left, limits.max_decompressed_bytes - 4);
        // Above the cap: rejected.
        bytes[4..8].copy_from_slice(&(MAX_SYSTEM_PAGE as u32 + 1).to_le_bytes());
        assert!(read_system_page(&bytes, 0, PAGE_MAP_TYPE, &mut budget, &mut c).is_err());
    }

    #[test]
    fn repeated_page_references_are_decompressed_once() {
        let payload: Vec<u8> = (1..=32).collect();
        let address = 0x100u64;
        let mut bytes = vec![0u8; 0x100];
        bytes.extend(data_page(address, &payload));
        let page_map = BTreeMap::from([(7i32, (address, bytes.len() as u64 - 0x100))]);
        // The same page under 500 references (same number, or other numbers mapping
        // to nothing), and a claimed size far beyond the data.
        let page = PageRef {
            page_number: 7,
            data_size: 32,
            start_offset: 0,
        };
        let info = SectionInfo {
            size: 1 << 40,
            max_page_size: 0x7400,
            compressed: 1,
            encrypted: 0,
            pages: vec![page; 500],
        };
        let limits = Limits::default();
        let mut budget = Budget::new(&limits);
        let mut c = Container::new(DwgVersion::R2004);
        let out = read_section(&bytes, "AcDb:Test", &info, &page_map, &mut budget, &mut c).unwrap();
        assert_eq!(out.get(..32), Some(&payload[..]));
        assert!(out.len() <= 32 + 64 * 0x7400);
        assert_eq!(
            limits.max_decompressed_bytes - budget.left,
            out.len() as u64
        );
        let dup = c
            .warnings
            .iter()
            .find(|w| w.code == "dwg.duplicate_page")
            .unwrap();
        assert!(dup.message.contains("499"), "{}", dup.message);
    }
}
