import os
from typing import Any, Dict, Iterator, List, Optional, Union

__version__: str

class CadkitError(Exception): ...
class UnknownFormatError(CadkitError): ...
class UnsupportedError(CadkitError): ...
class LimitExceededError(CadkitError): ...
class InvalidDataError(CadkitError): ...

class Document:
    @staticmethod
    def from_json(text: str) -> "Document": ...
    def to_dgn(self, seed: bytes, options_json: Optional[str] = None) -> bytes: ...
    def to_citygml(self, srs_name: str, lod: int = 1) -> bytes: ...
    def to_citygml_with_report(self, srs_name: str, lod: int = 1, metadata_only: bool = False) -> tuple[bytes, dict[str, Any]]: ...
    @property
    def format(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def application(self) -> Optional[str]: ...
    @property
    def codepage(self) -> Optional[str]: ...
    @property
    def units(self) -> Dict[str, Any]: ...
    @property
    def layers(self) -> List[Dict[str, Any]]: ...
    @property
    def blocks(self) -> List[Dict[str, Any]]: ...
    @property
    def models(self) -> List[Dict[str, Any]]: ...
    @property
    def warnings(self) -> List[Dict[str, Any]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self, pretty: bool = False) -> str: ...
    def to_svg(
        self,
        model: int = 0,
        width: float = 1600.0,
        stroke: float = 1.0,
        background: Optional[str] = "#ffffff",
        text: bool = True,
        expand_blocks: bool = True,
        images: bool = True,
    ) -> str: ...
    def to_dxf(self, version: str = "r2018") -> str: ...
    def entities(self, model: int = 0) -> Iterator[Dict[str, Any]]: ...

def read(
    source: Union[str, "os.PathLike[str]", bytes, bytearray, memoryview],
    *,
    keep_raw: bool = False,
    codepage: Optional[str] = None,
    max_input_bytes: Optional[int] = None,
    max_decompressed_bytes: Optional[int] = None,
    max_objects: Optional[int] = None,
    max_depth: Optional[int] = None,
) -> Document: ...
def detect(data: bytes) -> Optional[str]: ...

class CityGmlDocument:
    def preflight_tkgm(self, profile: str) -> dict[str, Any]: ...
    @staticmethod
    def from_json(text: str) -> "CityGmlDocument": ...
    def to_json(self) -> str: ...
    def to_gml(self, options_json: Optional[str] = None) -> bytes: ...
    def to_document(self, lod: Optional[int] = None) -> Document: ...
    def validate(self, options_json: Optional[str] = None) -> Dict[str, Any]: ...

def read_citygml(data: bytes, options_json: Optional[str] = None) -> CityGmlDocument: ...
