[package]
name = "cadkit-gml"
description = "Bounded CityGML 2.0 reader, writer and neutral geometry bridge."
version.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cadkit-core.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
