[package]
name = "cadkit-dgn"
description = "Clean-room DGN V7 and V8 reader and seed-based DGN V8 writer."
version.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cadkit-core.workspace = true
flate2.workspace = true
encoding_rs.workspace = true
cfb.workspace = true
serde.workspace = true

[lints]
workspace = true
